import type { TableElement, TablePreset } from "../../../types/elements";

export const TABLE_PRESETS: Record<TablePreset, Partial<TableElement>> = {
    minimal: {
        preset: "minimal",
        headerBg: "#f1f5f9",
        headerColor: "#0f172a",
        headerFontWeight: 600,
        rowBg: "#ffffff",
        altRowBg: "#f8fafc",
        cellColor: "#334155",
        borderColor: "#cbd5e1",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 6,
        shadow: "sm",
    },
    dark: {
        preset: "dark",
        headerBg: "#09090b",
        headerColor: "#fafafa",
        headerFontWeight: 600,
        rowBg: "#18181b",
        altRowBg: "#27272a",
        cellColor: "#e4e4e7",
        borderColor: "#3f3f46",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 8,
        shadow: "md",
    },
    ocean: {
        preset: "ocean",
        headerBg: "#1e40af",
        headerColor: "#ffffff",
        headerFontWeight: 600,
        rowBg: "#ffffff",
        altRowBg: "#eff6ff",
        cellColor: "#1e3a8a",
        borderColor: "#93c5fd",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 8,
        shadow: "sm",
    },
    emerald: {
        preset: "emerald",
        headerBg: "#065f46",
        headerColor: "#ffffff",
        headerFontWeight: 600,
        rowBg: "#ffffff",
        altRowBg: "#ecfdf5",
        cellColor: "#064e3b",
        borderColor: "#a7f3d0",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 8,
        shadow: "sm",
    },
    sunset: {
        preset: "sunset",
        headerBg: "#ea580c",
        headerColor: "#ffffff",
        headerFontWeight: 600,
        rowBg: "#ffffff",
        altRowBg: "#fff7ed",
        cellColor: "#7c2d12",
        borderColor: "#fed7aa",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 8,
        shadow: "sm",
    },
    classic: {
        preset: "classic",
        headerBg: "#e5e7eb",
        headerColor: "#111827",
        headerFontWeight: 600,
        rowBg: "#ffffff",
        altRowBg: "#ffffff",
        cellColor: "#111827",
        borderColor: "#4b5563",
        borderWidth: 1,
        borderStyle: "solid",
        borderRadius: 0,
        shadow: "none",
    },
};
