import type {
    PencilSettings,
    EraserSettings,
    DashboardBackgroundSettings,
    TextElement,
    TableElement,
    ClockElement,
    TimelineElement,
    CardElement,
    ButtonElement,
    IconElement,
} from "../types";

export const DEFAULT_PENCIL_SETTINGS: PencilSettings = {
    strokeWidth: 4,
    opacity: 1,
    color: "#000000",
    rotation: 0,
    size: 100,
};

export const DEFAULT_ERASER_SETTINGS: EraserSettings = {
    size: 30,
    opacity: 1,
};

export const DEFAULT_BACKGROUND_SETTINGS: DashboardBackgroundSettings = {
    type: "solid",
    color: "#ffffff",
    gradientType: "linear",
    gradientAngle: 135,
    gradientColor1: "#0f172a",
    gradientColor2: "#1e1b4b",
    imageUrl: "",
    imageFit: "cover",
    imageOpacity: 1,
    imageBlur: 0,
    imageOverlayColor: "#000000",
    imageOverlayOpacity: 0.2,
    showGridDots: true,
    gridDotsColor: "#b8b8b8",
    gridDotsSize: 20,
};

export function createTextElement(serialNumber: number): TextElement {
    return {
        id: crypto.randomUUID(),
        type: "text",
        serialNumber,
        x: 100,
        y: 100,
        text: "Text",
        fontSize: 24,
        color: "#000000",
        backgroundColor: "transparent",
        fontWeight: 400,
        fontFamily: "Arial",
        fontStyle: "normal",
        underline: false,
        rotation: 0,
    };
}

export function createTableElement(serialNumber: number): TableElement {
    return {
        id: crypto.randomUUID(),
        type: "table",
        serialNumber,
        x: 100,
        y: 120,
        rows: 3,
        cols: 3,
        headers: ["Column 1", "Column 2", "Column 3"],
        data: [
            ["Data 1-1", "Data 1-2", "Data 1-3"],
            ["Data 2-1", "Data 2-2", "Data 2-3"],
            ["Data 3-1", "Data 3-2", "Data 3-3"],
        ],
        hasHeader: true,
        preset: "minimal",
        headerBg: "#f1f5f9",
        headerColor: "#0f172a",
        headerFontWeight: 600,
        headerAlign: "left",
        rowBg: "#ffffff",
        altRowBg: "#f8fafc",
        cellColor: "#334155",
        cellAlign: "left",
        fontSize: 14,
        borderColor: "#cbd5e1",
        borderWidth: 1,
        borderStyle: "solid",
        cellPadding: 8,
        borderRadius: 6,
        shadow: "sm",
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}

export function createClockElement(serialNumber: number): ClockElement {
    const now = new Date();
    return {
        id: crypto.randomUUID(),
        type: "clock",
        serialNumber,
        x: 140,
        y: 140,
        design: "digital-minimal",
        timeMode: "live",
        customHour: now.getHours(),
        customMinute: now.getMinutes(),
        customSecond: now.getSeconds(),
        startEpochMs: Date.now(),
        is24Hour: false,
        showSeconds: true,
        showDate: true,
        dateMode: "live",
        customDateStr: now.toISOString().split("T")[0],
        bgColor: "#0f172a",
        textColor: "#f8fafc",
        accentColor: "#38bdf8",
        borderColor: "#334155",
        borderWidth: 1,
        borderRadius: 16,
        shadow: "md",
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}

export function createTimelineElement(serialNumber: number): TimelineElement {
    return {
        id: crypto.randomUUID(),
        type: "timeline",
        serialNumber,
        x: 120,
        y: 80,
        theme: "modern-vertical",
        items: [
            {
                id: crypto.randomUUID(),
                title: "B.Tech in Computer Science",
                subtitle: "Institute of Technology",
                date: "2020 - 2024",
                description:
                    "Graduated with Honors. Specialized in Cloud Computing and Modern Web Architectures.",
                tag: "Bachelor's Degree",
                icon: "graduation",
            },
            {
                id: crypto.randomUUID(),
                title: "Senior Full-Stack Engineer",
                subtitle: "HyperScale Tech Solutions",
                date: "2023 - Present",
                description:
                    "Architected modern design engine & canvas workspace. Scaled real-time collaboration pipeline.",
                tag: "Full-Time",
                icon: "briefcase",
            },
            {
                id: crypto.randomUUID(),
                title: "1st Prize - Global AI & Design Hackathon",
                subtitle: "International Open Innovate Summit",
                date: "Nov 2024",
                description:
                    "Built autonomous canvas design agents powered by Gemini AI, winning out of 3,500+ participants.",
                tag: "Award",
                icon: "trophy",
            },
        ],
        spacing: 24,
        nodeShape: "circle",
        nodeSize: 32,
        cardWidth: 480,
        cardMinHeight: 60,
        lineWidth: 2,
        lineColor: "#334155",
        animatedLine: false,
        accentColor: "#3b82f6",
        cardBg: "#0f172a",
        cardBorderColor: "#334155",
        cardBorderWidth: 1,
        borderRadius: 12,
        fontFamily: "Inter, sans-serif",
        titleColor: "#ffffff",
        titleFontSize: 15,
        titleFontWeight: 600,
        subtitleColor: "#94a3b8",
        subtitleFontSize: 12,
        dateColor: "#38bdf8",
        dateFontSize: 11,
        tagColor: "#3b82f6",
        tagFontSize: 10,
        textColor: "#e2e8f0",
        bodyFontSize: 12,
        shadow: "md",
        hoverEffect: "lift",
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}

export function createCardElement(serialNumber: number): CardElement {
    return {
        id: crypto.randomUUID(),
        type: "card",
        serialNumber,
        x: 140,
        y: 100,
        design: "neon-glow",
        cardWidth: 320,
        cardMinHeight: 220,
        cardBg: "#0f0f1a",
        cardBorderWidth: 1,
        cardBorderColor: "#334155",
        borderRadius: 16,
        shadow: "neon",
        accentColor: "#387ef0",
        heading: "Modern Card Component",
        headingColor: "#ffffff",
        headingFontSize: 20,
        headingFontWeight: 700,
        bodyText:
            "Create stunning glassmorphic and futuristic card components with customizable typography, colors, and interactive buttons.",
        bodyColor: "#94a3b8",
        bodyFontSize: 13,
        showButton: true,
        buttonText: "Explore More",
        buttonBgColor: "#387ef0",
        buttonTextColor: "#ffffff",
        buttonBorderRadius: 8,
        buttonFontSize: 13,
        buttonPaddingX: 18,
        buttonPaddingY: 9,
        buttonLink: "https://example.com",
        socialHandles: [
            { id: "1", platform: "github", label: "GitHub", url: "https://github.com" },
            { id: "2", platform: "twitter", label: "Twitter", url: "https://twitter.com" },
            { id: "3", platform: "linkedin", label: "LinkedIn", url: "https://linkedin.com" },
            { id: "4", platform: "discord", label: "Discord", url: "https://discord.com" },
            { id: "5", platform: "youtube", label: "YouTube", url: "https://youtube.com" },
            { id: "6", platform: "instagram", label: "Instagram", url: "https://instagram.com" },
        ],
        socialMarqueeSpeed: 20,
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}

export function createButtonElement(serialNumber: number): ButtonElement {
    return {
        id: crypto.randomUUID(),
        type: "button",
        serialNumber,
        x: 150,
        y: 120,
        theme: "button-1",
        text: "Button",
        link: "https://example.com",
        fontSize: 16,
        borderRadius: 8,
        borderRadiusUnit: "px",
        fontFamily: "Inter, sans-serif",
        paddingX: 24,
        paddingY: 12,
        bgColor: "transparent", // VERY IMPORTANT: default transparent as requested!
        bgImage: "",
        bgImageFit: "cover",
        bgImagePosition: "center",
        bgImageOpacity: 1,
        textColor: "#2c3e50",
        borderColor: "#3b82f6",
        borderWidth: 2,
        borderStyle: "solid",
        shadow: "none",
        shadowColor: "rgba(0, 0, 0, 0.35)",
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        shadowSpread: 0,
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}

export function createIconElement(serialNumber: number): IconElement {
    return {
        id: crypto.randomUUID(),
        type: "icon",
        serialNumber,
        x: 180,
        y: 160,
        iconType: "social",
        socialIconId: "instagram",
        avatarIconId: "dev-coder",
        emoji: "🚀",
        customImageUrl: "",
        customImageCrop: {
            x: 0,
            y: 0,
            scale: 1,
        },
        theme: "flat",
        enableLink: false,
        linkUrl: "https://instagram.com",
        removeBackground: false,
        width: 64,
        widthUnit: "px",
        height: 64,
        heightUnit: "px",
        iconColor: "#ffffff",
        useOriginalBrandColor: true,
        bgColor: "#18181b",
        borderColor: "#3f3f46",
        borderWidth: 0,
        borderStyle: "solid",
        borderRadius: 50,
        borderRadiusUnit: "%",
        padding: 12,
        shadow: "none",
        shadowColor: "rgba(0, 0, 0, 0.35)",
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        shadowSpread: 0,
        size: 100,
        rotation: 0,
        opacity: 1,
    };
}
